### ISSUE TITLE
Hybrid layout feature request: 2 screen option, no 3rd duplicate screen

### ISSUE THREAD

**Issue by n1ghttrap** [libretro/melonDS#119]
The 3rd, duplicate screen is just a little distracting to my eyes, and the desired result can be achieved in the Desmume core.  I imagine this is fairly trivial to implement.  Please consider it, thank you.

**Comment by m4tsa** [comment]
I believe it was @stuken that implemented it like that.

**Comment by stuken** [comment]
Will see if I can add it as a core option.

**Comment by SoloBackup** [comment]
this happened with me too in recent updates.

**Comment by m4tsa** [comment]
This should be fixed in the next build (which also contains a rebase of 0.9.3), it might take a day before it is available in the core updater. I added a core option letting you decide the placement of the small screen in hybrid mode and made the old behaivor default. Feel free to re-open if the issue persists.
