### ISSUE TITLE
Freeze and Crash on Close Content [Regression]

### ISSUE THREAD

**Issue by Awakened0** [libretro/melonDS#98]
The latest buildbot builds of the core after the Jan 16th rebase to 0.9.1 will freeze for a few seconds when closing content or exiting RetroArch. It does close after awhile, but I believe it's crashing because it doesn't write changed core options to file. This seems to only happen when using Vulkan as RetroArch's video driver (using software rendering in MelonDS). glcore doesn't have the issue. I've only tested on Windows, but one user on the Libretro Discord reported it happening on Android too. A few people have said it doesn't happen on Linux, but I haven't confirmed if they were using glcore or Vulkan.

One tip for reproducing this: If you've run the core with content using glcore before, you may need to restart your machine after switching to Vulkan for it to freeze. For some reason after I successfully ran the core without issue with glcore, the issue was gone in Vulkan until I restarted.

I have a previous 0.9 build of the core that doesn't have this issue. The git hash it shows is: 7bbf8e1

**Comment by Awakened0** [comment]
Two users have said on Discord they can reproduce this issue with glcore on Windows.

**Comment by bslenul** [comment]
Yeah, happens to me with glcore too, I have absolutely no clue what's causing this, I was super confused because I had the crash everytime 2 days ago but now it works fine for some reason, so I made a test yesterday on Windows: https://youtu.be/uc-qFQkaGMc

1st attempt I have RetroArch in G:\RA_TEST\RetroArch-Win64\ and no crash.
2nd attempt in G:\RA_TEST\test1\RetroArch-Win64\ = crash
G:\RA_TEST\test2\RetroArch-Win64\ = crash
G:\RA_TEST\bleh\RetroArch-Win64\ = no crash
G:\RA_TEST\waat\RetroArch-Win64\ = crash

And I'm just moving the whole folder, so it's the exact same settings/core options.
And then if somehow I can get it to work inside a specific folder, then it will always work after that from this folder (even after a reboot of the PC).

I tried with retroarch_debug.exe but it didn't create the crash log on crash :/

**Comment by m4tsa** [comment]
@bslenul

What version of the RetroArch frontend are you using, I tried with master and it seemed to be fairly unstable often crashing with null pointer dereferences, stable 1.8.0 seems to run fine for me.

**Comment by bslenul** [comment]
That was with the latest RA nightly from yesterday, but just tried with 1.8.0 and same result:

https://user-images.githubusercontent.com/33353403/105243094-dbf92300-5b6e-11eb-939a-893b5c6a6396.mp4

That's with everything to default (expect RA UI language). Tried the _debug.exe as well, still no crash log :/

**Comment by Immersion95** [comment]
I can also add these issues : 
-Opt Config file isn't created/updated
-Core doesn't change from Vulkan to GL/GLCore

**Comment by Ryunam** [comment]
I finally tested the latest code and can confirm what others have said. Core tends to be unstable right now, crashing often upon hitting the Close Content option on RA.

I've noticed the following:

- The crashes seem to happen only when using the OpenGL renderer. I've tried using the software renderer and repeatedly closing content a few seconds after starting it. I did not get any crash this way.
- With the OpenGL renderer, using all default settings other than the rendering resolution I'm getting **1 more frame of input latency** compared to how it was before the last rebase. I have an earlier version of the core backed up, dating back to December 3 2020, and with that version the GL renderer with the same settings reacts 1 frame earlier than the latest version.
- This is easily verifiable with the "pause and advance" (P+K) method on RetroArch. I have used the Japanese version of New Super Mario Bros., played with the OpenGL renderer at 2x the resolution and all the other core options set to their default values. When jumping, Mario reacts on the third frame with the December backup and on the fourth frame with the latest core from master.
- I've also had the core crash RA once while performing the P+K method to measure the latency frames.

**Comment by m4tsa** [comment]
Is anyone interested in compiling the core themselves with the newest mingw release? I just noticed someone replaced the entire Windows crossbuilding toolchain around new year. I remember the core used to have similar issues before due to outdated GCC versions emitting broken code when compiling using -O3.

**Comment by Ryunam** [comment]
I just performed a full update of MSYS2 and mingw, then compiled the core locally. Same issues as before: getting consistent crashes whenever hitting Close Content, as well as 1 frame of added input latency when using the GL renderer.

**Comment by bslenul** [comment]
Updated my MSYS2 setup as well (it says `gcc version 10.2.0 (Rev6, Built by MSYS2 project)`), I re-built the core and still the same crashes on close content for me too.

**Comment by trulystupidnewb** [comment]
I have this issue as well, regardless of using gl or vulkan. I'm using a Samsung Galaxy A51, and I noticed that melonds does not save core configurations. For example, I changed the screen layout to left/right instead of top/bottom, and it doesn't save on reboot. I also noticed the app crashes on closing content.

The app crashing is actually my lesser problematic issue. The main issue I have is that I cannot save core settings.

**Comment by Awakened0** [comment]
The latest Win64 nightly build isn't crashing anymore (closes immediately, changed core options save correctly). f6b775c7dbb7a5b3a5870ff30ca34c43d15ed9ba is probably what fixed it. Anyone who can test Linux and Android should see if it's fixed there too.

**Comment by Ryunam** [comment]
Crashes are gone here too! I'll soon open a separate issue about the extra flame of latency with the OpenGL renderer.

**Comment by bslenul** [comment]
Yeah no crash anymore on Windows 10, thank you m4tsa! 👍 

No crash on Android 32bit for me (but can't remember if it crashed before...) and no crash on my Linux VM with a "normal" build of RetroArch but it didn't crash previously so no changes.

I still get the crash on my Linux VM if I use RA built with `make DEBUG=1 SANITIZER=address,undefined`, but like I said in a previous reply this is maybe completely unrelated to this issue.

**Comment by Awakened0** [comment]
Alright, will close this then.
